version: "3.8"

services:
  nginx:
    image: nginx:alpine
    container_name: rinha_nginx
    ports:
      - "9999:9999"
    volumes:
      - ./api/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - payment-gateway-1
      - payment-gateway-2
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "50MB"
    networks:
      - backend
      - payment-processor    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9999"]
      interval: 30s
      timeout: 5s
      retries: 3

  payment-gateway-1:
    build: 
      context: .
      dockerfile: Dockerfile
    image: rinha-gateway:latest
    container_name: rinha_gateway_1
    hostname: rinha-gateway-1
    environment:
      - PAYMENT_PROCESSOR_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_FALLBACK=http://payment-processor-fallback:8080
      - GOMAXPROCS=4
      - GOGC=100
      - GOMEMLIMIT=150MiB
      - INSTANCE_ID=gateway-1
    deploy:
      resources:
        limits:
          cpus: "0.7"
          memory: "150MB"
    ulimits:
      nofile:
        soft: 100000
        hard: 100000
    sysctls:
        net.core.somaxconn: 65535
        net.ipv4.tcp_fin_timeout: 30
        net.ipv4.tcp_keepalive_time: 600
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "2"
    networks:
      - backend
      - payment-processor

  payment-gateway-2:
    build: 
      context: .
      dockerfile: Dockerfile
    image: rinha-gateway:latest
    container_name: rinha_gateway_2
    hostname: rinha-gateway-2
    environment:
      - PAYMENT_PROCESSOR_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_FALLBACK=http://payment-processor-fallback:8080
      - GOMAXPROCS=4
      - GOGC=100
      - GOMEMLIMIT=150MiB
      - INSTANCE_ID=gateway-2
    deploy:
      resources:
        limits:
          cpus: "0.7"
          memory: "150MB"
    ulimits:
      nofile:
        soft: 100000
        hard: 100000
    sysctls:
        net.core.somaxconn: 65535
        net.ipv4.tcp_fin_timeout: 30
        net.ipv4.tcp_keepalive_time: 600

    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "2"
    networks:
      - backend
      - payment-processor

networks:
  backend:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-rinha
  payment-processor:
    external: true